namespace: library
name: certs
version: 1.0.0

readme: README.md

authors:
- Josh Preston <joshuapreston@ucsb.edu>


### OPTIONAL but strongly recommended
description: Roles used in the acquisition and distribution of SSL Certificates.

license:
- GPL-2.0-or-later

license_file: ''
tags: [ucsb, library, certificates, certs, sectigo, acme]

dependencies: {}

repository: https://github.com/library-ucsb/library-ansible-collections-certs
documentation: http://www.ucsb.edu
homepage: http://www.ucsb.edu
issues: https://ucsb-atlas.atlassian.net/jira/software/projects/OPS
build_ignore: []

