---
# defaults file for sectigo

## Place the UCSB common attributes here


certs_default_key_size: 4096
certs_default_email: admins@domain.ucsb.edu
certs_default_country: US
certs_default_state: CA
certs_default_locality: Santa Barbara
certs_default_ou: University of California, Santa Barbara

certs_name: acme-default.domain.ucsb.edu
certs_cn: acme-default.domain.ucsb.edu
certs_sans: []

certs_acme_private_key:  acme-rsa-private-key-testing.pem
certs_acme_server_url:  "https://acme.sectigo.com/v2/InCommonRSAOV"

certs_acme_eab_alg: HS256
certs_acme_eab_key: 
certs_acme_eab_kid:

certs_key_size: 4096
#certs_key_passphrase: ## uncomment to use, but keep commented if not
#certs_key_cipher: ## need to assert something here if using a passphrase
certs_key_path: 'certs/'
certs_key_days: 90



# This is the passphrase used to 'unlock' this pkcs12 file.  It's not the same as the private key passphrase.
certs_pkcs12_cert_passphrase: 'changeit'
