# Certificates
certs_global:
  cert_storage_path: './certificates'
  directory_per_cert: true
  key_size: 4096
  suffix: private
  email: itops-admins@library.ucsb.edu

  common:
    certificate:
      country: US
      state: CA
      locality: Santa Barbara
      ou: University of California, Santa Barbara


